version: "3.9"
   
services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    ports:
      - '8080:8080'
    volumes:
      - ./trino/coordinator/etc:/etc/trino:ro
    networks:
      - trino-network

  trino-worker:
    image: 'trinodb/trino:latest'
    volumes:
      - ./trino/worker/etc:/etc/trino:ro
    networks:
      - trino-network
    deploy:
      mode: replicated
      replicas: 6

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - trino-network

networks:
  trino-network:
    driver: bridge

volumes:
  postgres-data:            
